"use client";

import { useState } from "react";

interface DossierDataProps {
  formulation: string;
  category: string;
  patentRoute: string;
  patentability: string;
  noveltyScore: number;
  statutoryBars: string[];
  mandatorySteps: string[];
}

export default function DossierExportButton({ data }: { data: DossierDataProps }) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExportDossier = () => {
    setIsExporting(true);

    const auditContent = `================================================================================
IP-SAKTI STATUTORY AUDIT & REGULATORY COMPLIANCE DOSSIER
Ministry of Ayush & Indian Patent Office (IPO) Statutory Framework
Generated On: ${new Date().toLocaleString()}
================================================================================

1. FORMULATION EVALUATED:
   Query / Ingredients: ${data.formulation || "N/A"}
   Assigned Regulatory Category: ${data.category}

2. STATUTORY IPR & PATENT EVALUATION:
   Patent Route: ${data.patentRoute}
   Patentability Status: ${data.patentability}
   TKDL vs Novelty Score: ${data.noveltyScore} / 100

3. STATUTORY GROUNDS & SECTIONS TRIGGERED:
   ${data.statutoryBars.length > 0 ? data.statutoryBars.map((b) => `- ${b}`).join("\n   ") : "- None (Clear of primary statutory bars)"}

4. MANDATORY REGULATORY COMPLIANCE STEPS:
   ${data.mandatorySteps.map((step, i) => `${i + 1}. ${step}`).join("\n   ")}

5. INTERNATIONAL & BIODIVERSITY COMPLIANCE (BDA 2024):
   - Access & Benefit Sharing (ABS): Rule 14 Form I filing mandated for commercial entities.
   - SBB Prior Intimation: Required prior to sourcing bio-resources.
   - Anti-Biopiracy Defensive Shield: Timestamped SHA-256 Prior Art hash verified.

================================================================================
OFFICIAL DISCLAIMER:
This digital dossier is generated by IP-SAKTI Regulatory Intelligence Engine.
It constitutes preliminary statutory guidance under Patents Act 1970 and BDA 2024.
================================================================================`;

    const blob = new Blob([auditContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `IP-SAKTI-Dossier-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setTimeout(() => setIsExporting(false), 800);
  };

  return (
    <button
      onClick={handleExportDossier}
      disabled={isExporting}
      className="w-full mt-4 py-2.5 px-4 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 hover:text-white text-xs font-semibold flex items-center justify-center gap-2 transition cursor-pointer disabled:opacity-50"
    >
      <span>📄</span>
      <span>{isExporting ? "Compiling Dossier..." : "Download Full Audit Dossier (.txt / Report)"}</span>
    </button>
  );
}